import * as monaco from 'monaco-editor/esm/vs/editor/editor.api'
export const githubDarkTheme: monaco.editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    {
      foreground: '8b949e',
      token: 'comment',
    },
    {
      foreground: '8b949e',
      token: 'punctuation.definition.comment',
    },
    {
      foreground: '8b949e',
      token: 'string.comment',
    },
    {
      foreground: '79c0ff',
      token: 'constant',
    },
    {
      foreground: '79c0ff',
      token: 'entity.name.constant',
    },
    {
      foreground: '79c0ff',
      token: 'variable.other.constant',
    },
    {
      foreground: '79c0ff',
      token: 'variable.language',
    },
    {
      foreground: '79c0ff',
      token: 'entity',
    },
    {
      foreground: 'ffa657',
      token: 'entity.name',
    },
    {
      foreground: 'e6edf3',
      token: 'variable.parameter.function',
    },
    {
      foreground: '7ee787',
      token: 'entity.name.tag',
    },
    {
      foreground: 'ff7b72',
      token: 'keyword',
    },
    {
      foreground: 'ff7b72',
      token: 'storage',
    },
    {
      foreground: 'ff7b72',
      token: 'storage.type',
    },
    {
      foreground: 'e6edf3',
      token: 'storage.modifier.package',
    },
    {
      foreground: 'e6edf3',
      token: 'storage.modifier.import',
    },
    {
      foreground: 'e6edf3',
      token: 'storage.type.java',
    },
    {
      foreground: 'a5d6ff',
      token: 'string',
    },
    {
      foreground: 'a5d6ff',
      token: 'punctuation.definition.string',
    },
    {
      foreground: 'a5d6ff',
      token: 'string punctuation.section.embedded source',
    },
    {
      foreground: '79c0ff',
      token: 'support',
    },
    {
      foreground: '79c0ff',
      token: 'meta.property-name',
    },
    {
      foreground: 'ffa657',
      token: 'variable',
    },
    {
      foreground: 'e6edf3',
      token: 'variable.other',
    },
    {
      foreground: 'ffa198',
      fontStyle: 'italic',
      token: 'invalid.broken',
    },
    {
      foreground: 'ffa198',
      fontStyle: 'italic',
      token: 'invalid.deprecated',
    },
    {
      foreground: 'ffa198',
      background: 'd73a49',
      fontStyle: 'italic',
      token: 'invalid.illegal',
    },
    {
      foreground: 'f0f6fc',
      background: 'ff7b72',
      fontStyle: 'italic underline',
      token: 'carriage-return',
    },
    {
      foreground: 'ffa198',
      fontStyle: 'italic',
      token: 'invalid.unimplemented',
    },
    {
      foreground: 'ffa198',
      token: 'message.error',
    },
    {
      foreground: 'a5d6ff',
      token: 'string source',
    },
    {
      foreground: '79c0ff',
      token: 'string variable',
    },
    {
      foreground: 'a5d6ff',
      token: 'source.regexp',
    },
    {
      foreground: 'a5d6ff',
      token: 'string.regexp',
    },
    {
      foreground: 'a5d6ff',
      token: 'string.regexp.character-class',
    },
    {
      foreground: 'a5d6ff',
      token: 'string.regexp constant.character.escape',
    },
    {
      foreground: 'a5d6ff',
      token: 'string.regexp source.ruby.embedded',
    },
    {
      foreground: 'a5d6ff',
      token: 'string.regexp string.regexp.arbitrary-repitition',
    },
    {
      foreground: 'a5d6ff',
      fontStyle: 'bold',
      token: 'string.regexp constant.character.escape',
    },
    {
      foreground: '79c0ff',
      token: 'support.constant',
    },
    {
      foreground: '79c0ff',
      token: 'support.variable',
    },
    {
      foreground: '79c0ff',
      token: 'meta.module-reference',
    },
    {
      foreground: '79c0ff',
      token: 'markup.list',
    },
    {
      foreground: '79c0ff',
      fontStyle: 'bold',
      token: 'markup.heading',
    },
    {
      foreground: '79c0ff',
      fontStyle: 'bold',
      token: 'markup.heading entity.name',
    },
    {
      foreground: '7ee787',
      token: 'markup.quote',
    },
    {
      foreground: 'e6edf3',
      fontStyle: 'italic',
      token: 'markup.italic',
    },
    {
      foreground: 'e6edf3',
      fontStyle: 'bold',
      token: 'markup.bold',
    },
    {
      foreground: 'ffa198',
      background: '490202',
      token: 'markup.deleted',
    },
    {
      foreground: 'ffa198',
      background: '490202',
      token: 'meta.diff.header.from-file',
    },
    {
      foreground: 'b31d28',
      background: '490202',
      token: 'punctuation.definition.deleted',
    },
    {
      foreground: '7ee787',
      background: '04260f',
      token: 'markup.inserted',
    },
    {
      foreground: '7ee787',
      background: '04260f',
      token: 'meta.diff.header.to-file',
    },
    {
      foreground: '7ee787',
      background: '04260f',
      token: 'punctuation.definition.inserted',
    },
    {
      foreground: 'ffa657',
      background: '5a1e02',
      token: 'markup.changed',
    },
    {
      foreground: 'ffa657',
      background: '5a1e02',
      token: 'punctuation.definition.changed',
    },
    {
      foreground: '161b22',
      background: '79c0ff',
      token: 'markup.ignored',
    },
    {
      foreground: '161b22',
      background: '79c0ff',
      token: 'markup.untracked',
    },
    {
      foreground: 'd2a8ff',
      fontStyle: 'bold',
      token: 'meta.diff.range',
    },
    {
      foreground: '79c0ff',
      token: 'meta.diff.header',
    },
    {
      foreground: '79c0ff',
      fontStyle: 'bold',
      token: 'meta.separator',
    },
    {
      foreground: '79c0ff',
      token: 'meta.output',
    },
    {
      foreground: '8b949e',
      token: 'brackethighlighter.tag',
    },
    {
      foreground: '8b949e',
      token: 'brackethighlighter.curly',
    },
    {
      foreground: '8b949e',
      token: 'brackethighlighter.round',
    },
    {
      foreground: '8b949e',
      token: 'brackethighlighter.square',
    },
    {
      foreground: '8b949e',
      token: 'brackethighlighter.angle',
    },
    {
      foreground: '8b949e',
      token: 'brackethighlighter.quote',
    },
    {
      foreground: 'ffa198',
      token: 'brackethighlighter.unmatched',
    },
    {
      foreground: 'a5d6ff',
      token: 'constant.other.reference.link',
    },
    {
      foreground: 'a5d6ff',
      token: 'string.other.link',
    },
  ],
  colors: {
    focusBorder: '#1f6feb',
    foreground: '#e6edf3',
    descriptionForeground: '#7d8590',
    errorForeground: '#f85149',
    'textLink.foreground': '#2f81f7',
    'textLink.activeForeground': '#2f81f7',
    'textBlockQuote.background': '#010409',
    'textBlockQuote.border': '#30363d',
    'textCodeBlock.background': '#6e768166',
    'textPreformat.foreground': '#7d8590',
    'textPreformat.background': '#6e768166',
    'textSeparator.foreground': '#21262d',
    'icon.foreground': '#7d8590',
    'keybindingLabel.foreground': '#e6edf3',
    'button.background': '#238636',
    'button.foreground': '#ffffff',
    'button.hoverBackground': '#2ea043',
    'button.secondaryBackground': '#282e33',
    'button.secondaryForeground': '#c9d1d9',
    'button.secondaryHoverBackground': '#30363d',
    'checkbox.background': '#161b22',
    'checkbox.border': '#30363d',
    'dropdown.background': '#161b22',
    'dropdown.border': '#30363d',
    'dropdown.foreground': '#e6edf3',
    'dropdown.listBackground': '#161b22',
    'input.background': '#0d1117',
    'input.border': '#30363d',
    'input.foreground': '#e6edf3',
    'input.placeholderForeground': '#6e7681',
    'badge.foreground': '#ffffff',
    'badge.background': '#1f6feb',
    'editor.foreground': '#e6edf3',
    'editor.background': '#0d1117',
    'editorWidget.background': '#161b22',
    'editor.foldBackground': '#6e76811a',
    'editor.lineHighlightBackground': '#6e76811a',
    'editorLineNumber.foreground': '#6e7681',
    'editorLineNumber.activeForeground': '#e6edf3',
    'editorIndentGuide.background': '#e6edf31f',
    'editorIndentGuide.activeBackground': '#e6edf33d',
    'editorWhitespace.foreground': '#484f58',
    'editorCursor.foreground': '#2f81f7',
    'editor.findMatchBackground': '#9e6a03',
    'editor.findMatchHighlightBackground': '#f2cc6080',
    'editor.linkedEditingBackground': '#2f81f712',
    'editor.selectionHighlightBackground': '#3fb95040',
    'editor.wordHighlightBackground': '#6e768180',
    'editor.wordHighlightBorder': '#6e768199',
    'editor.wordHighlightStrongBackground': '#6e76814d',
    'editor.wordHighlightStrongBorder': '#6e768199',
    'editorBracketMatch.background': '#3fb95040',
    'editorBracketMatch.border': '#3fb95099',
    'editorInlayHint.background': '#8b949e33',
    'editorInlayHint.foreground': '#7d8590',
    'editorInlayHint.typeBackground': '#8b949e33',
    'editorInlayHint.typeForeground': '#7d8590',
    'editorInlayHint.paramBackground': '#8b949e33',
    'editorInlayHint.paramForeground': '#7d8590',
    'scrollbar.shadow': '#484f5833',
    'scrollbarSlider.background': '#8b949e33',
    'scrollbarSlider.hoverBackground': '#8b949e3d',
    'scrollbarSlider.activeBackground': '#8b949e47',
    'editorOverviewRuler.border': '#010409',
    'editorBracketHighlight.foreground1': '#79c0ff',
    'editorBracketHighlight.foreground2': '#56d364',
    'editorBracketHighlight.foreground3': '#e3b341',
    'editorBracketHighlight.foreground4': '#ffa198',
    'editorBracketHighlight.foreground5': '#ff9bce',
    'editorBracketHighlight.foreground6': '#d2a8ff',
    'editorBracketHighlight.unexpectedBracket.foreground': '#7d8590',
    'editor.stackFrameHighlightBackground': '#bb800966',
    'editor.focusedStackFrameHighlightBackground': '#2ea04366',
    'editorCodeLens.foreground': '#e6edf3',
    'editorLink.activeForeground': '#e6edf3',
  },
}
